name: Zip and Release Obsidian Template

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.CI_KEY }}

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: obsidian-template.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CI_KEY }}
